### ISSUE TITLE
error while starting aker

### ISSUE THREAD

**Issue by shiblovich** [aker-gateway/Aker#110]
when i trying to start aker i got this error 
#python aker.py
Traceback (most recent call last):
  File "aker.py", line 180, in <module>
    Aker().build_tui()
  File "aker.py", line 111, in __init__
    config = Configuration(config_file)
  File "aker.py", line 60, in __init__
    self.log_level = self.configparser.get('General', 'log_level')
  File "/usr/lib/python2.7/site-packages/backports/configparser/__init__.py", line 858, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python2.7/site-packages/backports/configparser/__init__.py", line 1228, in _unify_values
    raise NoSectionError(section)
backports.configparser.NoSectionError: No section: 'General'
----------------------------------
what should i do and we need a reference video for how to install or how start with this tool . 
thank you

**Comment by anazmy** [comment]
This[1] playbook does take care of the installation.
Your error implies you do not have a complete `/etc/aker/aker.ini`. Can you please paste this file content

[1] https://github.com/aker-gateway/aker-freeipa-playbook

**Comment by shiblovich** [comment]
could you please make a video for how to install and use aker ?
we need this tool very much
