### ISSUE TITLE
doenst run out of the box on deb7

### ISSUE THREAD

**Issue by rogerthat** [aker-gateway/Aker#5]
i followed you installation-instruction

```
python aker.py 
Traceback (most recent call last):
  File "aker.py", line 137, in <module>
    Aker().build_tui()
  File "aker.py", line 99, in __init__
    self.build_tui()
  File "aker.py", line 105, in build_tui
    self.tui = tui.Window(self)
  File "/home/mex/data/svn/Aker/tui.py", line 43, in __init__
    self.draw()
  File "/home/mex/data/svn/Aker/tui.py", line 96, in draw
    self.hosts_listbox = self.refresh_hosts(self.aker.user.ssh_hosts)
  File "/home/mex/data/svn/Aker/tui.py", line 53, in refresh_hosts
    return urwid.ListBox(urwid.SimpleFocusListWalker(body))
AttributeError: 'module' object has no attribute 'SimpleFocusListWalker'
```

**Comment by anazmy** [comment]
I think urwid package on Debian doesn't have required features - gotta verify that though -  can you try installing urwid from source?

**Comment by rogerthat** [comment]
i will try install urwid via virtualenv
