### ISSUE TITLE
no attribute ssession_end_callback

### ISSUE THREAD

**Issue by sholan** [aker-gateway/Aker#6]
Trace : 
`Traceback (most recent call last):
  File "/bin/aker/aker.py", line 137, in <module>
    Aker().build_tui()
  File "/bin/aker/aker.py", line 99, in __init__
    self.build_tui()
  File "/bin/aker/aker.py", line 107, in build_tui
    self.tui.start()
  File "/bin/aker/tui.py", line 147, in start
    self.loop.run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python2.7/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python2.7/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python2.7/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python2.7/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python2.7/site-packages/urwid/listbox.py", line 987, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/bin/aker/tui.py", line 27, in keypress
    urwid.emit_signal(self, 'connect')
  File "/usr/lib/python2.7/site-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python2.7/site-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/bin/aker/tui.py", line 61, in host_chosen
    self.aker.init_connection(choice)
  File "/bin/aker/aker.py", line 124, in init_connection
    session.start_session()
  File "/bin/aker/session.py", line 60, in start_session
    self._client.start_session(self.host_user,priv_key)
  File "/bin/aker/SSHClient.py", line 56, in start_session
    self._session.close_session()
  File "/bin/aker/session.py", line 38, in close_session
    self.aker.ssession_end_callback(self)
AttributeError: 'Aker' object has no attribute 'ssession_end_callback'
`

Happens upon disconnecting from private instance.
Maybe a typo (ss instead of s) ?

**Comment by anazmy** [comment]
Thanks sholan, yup another typo, I merged your change
