### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by 11philip22** [aker-gateway/Aker#60]
i installed aker but when i ssh in i get this:
philip@192.168.1.111's password: 
Traceback (most recent call last):
  File "/usr/bin/aker/aker.py", line 168, in <module>
    Aker().build_tui()
  File "/usr/bin/aker/aker.py", line 105, in __init__
    config = Configuration(config_file)
  File "/usr/bin/aker/aker.py", line 54, in __init__
    self.log_level = self.configparser.get('General', 'log_level')
  File "/usr/lib/python2.7/dist-packages/backports/configparser/__init__.py", line 792, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python2.7/dist-packages/backports/configparser/__init__.py", line 1162, in _unify_values
    raise NoSectionError(section)
backports.configparser.NoSectionError: No section: 'General'
Connection to 192.168.1.111 closed.

**Comment by anazmy** [comment]
Is /etc/aker/aker.ini in place ?
What are the contents of /etc/aker/aker.ini ?

**Comment by 11philip22** [comment]
i see there is no aker.ini so i will copy it over

**Comment by 11philip22** [comment]
I see i dont a aker folder in /etc/ so i made that and copied aker.ini over.
I also see i dont have a hosts.json file so i also copied that.
So currently i have a hosts.json and a aker.ini file in my /etc/aker/ folder do i need other files?

**Comment by anazmy** [comment]
Nope that should be it, if you're not using IPA make sure to choose json in aker.ini

**Comment by Seculin** [comment]
after doing same steps I got this 
`Traceback (most recent call last):
  File "aker.py", line 152, in <module>
    Aker().build_tui()
  File "aker.py", line 114, in __init__
    logging.basicConfig(format='%(asctime)s - %(levelname)s - %(message)s',filename=log_file,level=config.log_level)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1545, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 941, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/var/log/aker/aker.log'`

**Comment by anazmy** [comment]
Seems you don't have the logs dir created, whats output of
`find /var/log/aker/ -ls`

**Comment by anazmy** [comment]
no update for a while, closing issue.
