### ISSUE TITLE
Error log on closing connection through Aker jumpserver

### ISSUE THREAD

**Issue by JanHamara** [aker-gateway/Aker#63]
Hi there, I have got Aker configured and functioning correctly for login to server (so far tested with localhost, thus connecting to jumpserver itself), however on exiting Aker (with 'exit' as root, I get this error report)... does this mean there is something wrong with configuration or is it just that I am trying to access jumpserver itself via Aker ? (to be clear I logged in as root and ran 'python /usr/bin/aker/aker.py)

Error report:

`  File "/usr/bin/aker/aker.py", line 168, in <module>
    Aker().build_tui()
  File "/usr/bin/aker/aker.py", line 130, in build_tui
    self.tui.start()
  File "/usr/bin/aker/tui.py", line 344, in start
    self.loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python2.7/dist-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/bin/aker/tui.py", line 76, in keypress
    self.focus.original_widget.get_caption())
AttributeError: 'NoneType' object has no attribute 'original_widget'`

Also...

If I login as another user (etc. admin), I get Aker UI (obviously) and login to jumpserver, I get Aker UI again (still quite obviously because logging to jumpserver even through jumpserver shouldn't make server not to run aker.py automatically), however after exiting I get a little bit different error log:

`Traceback (most recent call last):
  File "/usr/bin/aker/aker.py", line 168, in <module>
    Aker().build_tui()
  File "/usr/bin/aker/aker.py", line 130, in build_tui
    self.tui.start()
  File "/usr/bin/aker/tui.py", line 344, in start
    self.loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 706, in _loop
    ready, w, err = select.select(fds, [], fds)
KeyboardInterrupt
Connection to bastion.seculin.com closed.`

I believe this is just because of my interruption and my attempt to login multiple times to same server, right?

**Comment by anazmy** [comment]
Hi Jan,
Aker is meant to be used to connect to other servers, can you please test connecting to other servers rather than localhost.

**Comment by Seculin** [comment]
Hi Anazmy,

I have connected to another server succesfully, executed few commands to be recorded in the session and after exiting from server back to Aker, I got back to UI, after quitting from UI, I get this error log and connection to Aker server closes....

File "/usr/bin/aker/aker.py", line 168, in <module>
    Aker().build_tui()
  File "/usr/bin/aker/aker.py", line 130, in build_tui
    self.tui.start()
  File "/usr/bin/aker/tui.py", line 344, in start
    self.loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python2.7/dist-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/bin/aker/tui.py", line 76, in keypress
    self.focus.original_widget.get_caption())
AttributeError: 'NoneType' object has no attribute 'original_widget'

**Comment by anazmy** [comment]
@seculin, which urwid version are you using?

**Comment by anazmy** [comment]
Closed due to lack of updates. Feel free to reopen if needed.
