### ISSUE TITLE
I have error whene i try to connect to server 

### ISSUE THREAD

**Issue by v3rlust** [aker-gateway/Aker#65]
i use fedora 27 i build everything correctly 
i installed every package "urwid ......" 
u had a big probleme whene i try to connect to server from bastien server 
i think the error is in urwid
 ``
Traceback (most recent call last):
  File "/usr/bin/aker/aker.py", line 168, in <module>
    Aker().build_tui()
  File "/usr/bin/aker/aker.py", line 130, in build_tui
    self.tui.start()
  File "/usr/bin/aker/tui.py", line 344, in start
    self.loop.run()
  File "/usr/lib64/python2.7/site-packages/urwid/main_loop.py", line 277, in run
    self._run()
  File "/usr/lib64/python2.7/site-packages/urwid/main_loop.py", line 374, in _run
    self.event_loop.run()
  File "/usr/lib64/python2.7/site-packages/urwid/main_loop.py", line 677, in run
    self._loop()
  File "/usr/lib64/python2.7/site-packages/urwid/main_loop.py", line 714, in _loop
    self._watch_files[fd]()
  File "/usr/lib64/python2.7/site-packages/urwid/raw_display.py", line 391, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib64/python2.7/site-packages/urwid/raw_display.py", line 491, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib64/python2.7/site-packages/urwid/main_loop.py", line 398, in _update
    self.process_input(keys)
  File "/usr/lib64/python2.7/site-packages/urwid/main_loop.py", line 498, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib64/python2.7/site-packages/urwid/wimp.py", line 642, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib64/python2.7/site-packages/urwid/container.py", line 1127, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib64/python2.7/site-packages/urwid/container.py", line 1127, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/bin/aker/tui.py", line 76, in keypress
    self.focus.original_widget.get_caption())
  File "/usr/lib64/python2.7/site-packages/urwid/signals.py", line 263, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib64/python2.7/site-packages/urwid/signals.py", line 293, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/bin/aker/tui.py", line 326, in host_chosen_handler
    self.aker.init_connection(host)
  File "/usr/bin/aker/aker.py", line 155, in init_connection
    session.stop_sniffer()
  File "/usr/bin/aker/session.py", line 37, in stop_sniffer
    self._client.stop_sniffer()
  File "/usr/bin/aker/SSHClient.py", line 38, in stop_sniffer
    sniffer.stop()
  File "/usr/bin/aker/snoop.py", line 164, in stop
    self.log_file.write('Session End %s' % session_end)
AttributeError: 'NoneType' object has no attribute 'write'
``

**Comment by anazmy** [comment]
Can you provide version of urwid used and your aker.ini configuration please

**Comment by v3rlust** [comment]
actually i found the probleme it was  the probleme with urwid version 
last version urwid doesn't work with it 
but can i ask you question ? 
can we load hosts directly from the file json.host without passing with redis ??

**Comment by anazmy** [comment]
I thought so, which version of urwid ur using?

**Comment by v3rlust** [comment]
i was using the last version 2.0.1 however there is a problem with it so i tried to install another wich is 1.2 and it works fine now

**Comment by anazmy** [comment]
OK, great you got it sorted, I'm closing this issue till I get latest urwid version tested.
