### ISSUE TITLE
Can't connect through SSH after Match Group *,!root ForceCommand /usr/bin/aker/aker.py

### ISSUE THREAD

**Issue by hariharry** [aker-gateway/Aker#77]
Finished the step "Match Group *,!root
ForceCommand /usr/bin/aker/aker.py"
after that server connection timed out when i try to reconnect its showing following error
_```
X11 forwarding request failed on channel 0
Traceback (most recent call last):
  File "/usr/bin/aker/aker.py", line 174, in <module>
    Aker().build_tui()
  File "/usr/bin/aker/aker.py", line 130, in __init__
    self.user = User(self.posix_user)
  File "/usr/bin/aker/aker.py", line 81, in __init__
    self.hosts = Hosts(config, self.name, gateway_hostgroup, idp)
  File "/usr/bin/aker/hosts.py", line 88, in __init__
    self.idp = IdPFactory.getIdP(idp)(config, username, gateway_hostgroup)
  File "/usr/bin/aker/IdPFactory.py", line 35, in getIdP
    return idp_class
UnboundLocalError: local variable 'idp_class' referenced before assignment
```_

**Comment by anazmy** [comment]
Can you paste your aker.ini here please.
Also, attach /var/log/aker/aker.log with debug logging "**log_level = DEBUG**" set in aker.ini

**Comment by hariharry** [comment]
aker.ini file 

`[General]
log_level = INFO
ssh_port = 22

 -Identity Provider to determine the list of available hosts
-options shipped are IPA, Json. Default is IPA
idp = IPA
hosts_file = /etc/aker/hosts.json

 -FreeIPA hostgroup name contatining Aker gateways
 -to be excluded from hosts presented to user
gateway_group = gateways`

below is the aker.log file's few entry

`
2018-07-02 18:39:47,768 - ERROR - IdPFactory: error loading module : No module named pyhbac
2018-07-03 05:03:11,775 - INFO - Core: Starting up, user=ec2-user from=43.224.156.153:59892
2018-07-03 05:03:11,775 - INFO - IdPFactory: trying dynamic loading of module : IPA
2018-07-03 05:03:11,776 - ERROR - IdPFactory: error loading module : No module named pyhbac
2018-07-03 05:08:34,147 - INFO - Core: Starting up, user=ec2-user from=43.224.156.153:60016
2018-07-03 05:08:34,147 - INFO - IdPFactory: trying dynamic loading of module : IPA
2018-07-03 05:08:34,148 - ERROR - IdPFactory: error loading module : No module named pyhbac
2018-07-03 07:15:15,964 - INFO - Core: Starting up, user=ec2-user from=43.224.156.153:61011
2018-07-03 07:15:15,964 - INFO - IdPFactory: trying dynamic loading of module : IPA
2018-07-03 07:15:15,965 - ERROR - IdPFactory: error loading module : No module named pyhbac
2018-07-03 09:53:16,637 - INFO - Core: Starting up, user=ec2-user from=43.224.156.153:62643
2018-07-03 09:53:16,637 - INFO - IdPFactory: trying dynamic loading of module : IPA
2018-07-03 09:53:16,638 - ERROR - IdPFactory: error loading module : No module named pyhbac
2018-07-03 09:53:23,484 - INFO - Core: Starting up, user=ec2-user from=43.224.156.153:62645
2018-07-03 09:53:23,485 - INFO - IdPFactory: trying dynamic loading of module : IPA
2018-07-03 09:53:23,486 - ERROR - IdPFactory: error loading module : No module named pyhbac
2018-07-03 11:59:56,491 - INFO - Core: Starting up, user=ec2-user from=43.224.156.153:64157
2018-07-03 11:59:56,491 - INFO - IdPFactory: trying dynamic loading of module : IPA
2018-07-03 11:59:56,492 - ERROR - IdPFactory: error loading module : No module named pyhbac
2018-07-03 12:00:03,646 - INFO - Core: Starting up, user=ec2-user from=43.224.156.153:64158
2018-07-03 12:00:03,646 - INFO - IdPFactory: trying dynamic loading of module : IPA
2018-07-03 12:00:03,647 - ERROR - IdPFactory: error loading module : No module named pyhbac
2018-07-03 14:31:05,805 - INFO - Core: Starting up, user=ec2-user from=27.7.17.231:49412
2018-07-03 14:31:05,805 - INFO - IdPFactory: trying dynamic loading of module : IPA
2018-07-03 14:31:05,806 - ERROR - IdPFactory: error loading module : No module named pyhbac`

**Comment by y3lin4ung** [comment]
> aker.ini file
> 
> `[General]
> log_level = INFO
> ssh_port = 22
> 
> -Identity Provider to determine the list of available hosts
> -options shipped are IPA, Json. Default is IPA
> idp = IPA
> hosts_file = /etc/aker/hosts.json
> 
> -FreeIPA hostgroup name contatining Aker gateways
> -to be excluded from hosts presented to user
> gateway_group = gateways`
> 
> below is the aker.log file's few entry
> 
> ` 2018-07-02 18:39:47,768 - ERROR - IdPFactory: error loading module : No module named pyhbac 2018-07-03 05:03:11,775 - INFO - Core: Starting up, user=ec2-user from=43.224.156.153:59892 2018-07-03 05:03:11,775 - INFO - IdPFactory: trying dynamic loading of module : IPA 2018-07-03 05:03:11,776 - ERROR - IdPFactory: error loading module : No module named pyhbac 2018-07-03 05:08:34,147 - INFO - Core: Starting up, user=ec2-user from=43.224.156.153:60016 2018-07-03 05:08:34,147 - INFO - IdPFactory: trying dynamic loading of module : IPA 2018-07-03 05:08:34,148 - ERROR - IdPFactory: error loading module : No module named pyhbac 2018-07-03 07:15:15,964 - INFO - Core: Starting up, user=ec2-user from=43.224.156.153:61011 2018-07-03 07:15:15,964 - INFO - IdPFactory: trying dynamic loading of module : IPA 2018-07-03 07:15:15,965 - ERROR - IdPFactory: error loading module : No module named pyhbac 2018-07-03 09:53:16,637 - INFO - Core: Starting up, user=ec2-user from=43.224.156.153:62643 2018-07-03 09:53:16,637 - INFO - IdPFactory: trying dynamic loading of module : IPA 2018-07-03 09:53:16,638 - ERROR - IdPFactory: error loading module : No module named pyhbac 2018-07-03 09:53:23,484 - INFO - Core: Starting up, user=ec2-user from=43.224.156.153:62645 2018-07-03 09:53:23,485 - INFO - IdPFactory: trying dynamic loading of module : IPA 2018-07-03 09:53:23,486 - ERROR - IdPFactory: error loading module : No module named pyhbac 2018-07-03 11:59:56,491 - INFO - Core: Starting up, user=ec2-user from=43.224.156.153:64157 2018-07-03 11:59:56,491 - INFO - IdPFactory: trying dynamic loading of module : IPA 2018-07-03 11:59:56,492 - ERROR - IdPFactory: error loading module : No module named pyhbac 2018-07-03 12:00:03,646 - INFO - Core: Starting up, user=ec2-user from=43.224.156.153:64158 2018-07-03 12:00:03,646 - INFO - IdPFactory: trying dynamic loading of module : IPA 2018-07-03 12:00:03,647 - ERROR - IdPFactory: error loading module : No module named pyhbac 2018-07-03 14:31:05,805 - INFO - Core: Starting up, user=ec2-user from=27.7.17.231:49412 2018-07-03 14:31:05,805 - INFO - IdPFactory: trying dynamic loading of module : IPA 2018-07-03 14:31:05,806 - ERROR - IdPFactory: error loading module : No module named pyhbac`

why don't you try to remove python (especially '/usr/bin/env python' ) and retry brother?
