### ISSUE TITLE
Cannot start aker

### ISSUE THREAD

**Issue by nfieric** [aker-gateway/Aker#87]
I receive the below error when trying to start aker.py. CentOS7, Python 2.7.5. Any idea why this would be occurring?

[root@localhost aker]# ./aker.py
Traceback (most recent call last):
  File "./aker.py", line 174, in <module>
    Aker().build_tui()
  File "./aker.py", line 130, in __init__
    self.user = User(self.posix_user)
  File "./aker.py", line 81, in __init__
    self.hosts = Hosts(config, self.name, gateway_hostgroup, idp)
  File "/usr/bin/aker/hosts.py", line 88, in __init__
    self.idp = IdPFactory.getIdP(idp)(config, username, gateway_hostgroup)
  File "/usr/bin/aker/IdPFactory.py", line 35, in getIdP
    return idp_class
UnboundLocalError: local variable 'idp_class' referenced before assignment

**Comment by anazmy** [comment]
What is the content of "/etc/aker/aker.ini" ?

Also, aker is not meant to be ran in that way. Please check the readme for details of the installation. Ideally you should have aker enforced  on sshd side: _ForceCommand /usr/bin/aker/aker.py_
